FROM ghcr.io/symfony-cli/symfony-cli:v5 AS symfony-cli

FROM dunglas/frankenphp:1.12-php8 AS dev
WORKDIR /app

# Deps for PDO_MYSQL and INTL
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml2-dev zlib1g-dev libzip-dev libfreetype6-dev libpng-dev libwebp-dev libxpm-dev \
    libpq-dev libjpeg-dev libjpeg62-turbo-dev libicu-dev libgd-dev libonig-dev libxslt1-dev \
    && docker-php-ext-install pdo pdo_mysql intl zip sockets calendar mbstring exif gd xsl mysqli \
    && docker-php-ext-configure intl \
    && docker-php-ext-configure gd --enable-gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ --with-webp=/usr/include/ \
    && docker-php-ext-enable intl

# Install Symfony CLI and Composer
COPY --link --from=symfony-cli /usr/local/bin/symfony /usr/local/bin/symfony
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
